//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autenticacao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int LoginId { get; set; }
        public string LoginNome { get; set; }
        public string LoginSenha { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
    }
}
