//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autenticacao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Logins = new HashSet<Login>();
        }
    
        public int RoleId { get; set; }
        public string RoleNome { get; set; }
    
        public virtual ICollection<Login> Logins { get; set; }
    }
}
